### ISSUE TITLE
zh_CN application name file garbled

### ISSUE THREAD

**Issue by VergeDX** [liri-project/liri-text#60] opened 2020-06-18 12:04 UTC
As the title said, so I found .desktop file like this:  
![image](https://user-images.githubusercontent.com/25173827/85017891-d1bd1380-b19e-11ea-86d3-0f4a575b67e6.png)
And you see, zh_CN & zh_TW translate string is garbled, idk why It would be like this...

**Comment by VergeDX** [comment] 2020-06-18 12:06
And also, the application name in gnome like this:  
![image](https://user-images.githubusercontent.com/25173827/85018074-29f41580-b19f-11ea-95e7-8b386701701d.png)

**Comment by Aldrog** [comment] 2020-06-19 09:35
I can confirm since 77d72095f45c0a2ad9545df6a80aa356e42887a0 all non-ASCII characters in the .desktop file are corrupted. @plfiorini is something wrong with gettext usage? The .po files seem to be correct UTF-8.

**Comment by plfiorini** [comment] 2020-06-19 10:19
`intltool` is used to merge the .po files: https://github.com/liri-infra/translation-action/blob/master/entrypoint#L54

**Comment by plfiorini** [comment] 2020-06-19 10:20
https://manpages.debian.org/stretch/intltool/intltool-merge.8.en.html

There's a `--utf8` switch maybe it helps.

**Comment by plfiorini** [comment] 2020-06-19 11:02
Tested calling `intltool-merge` with '--utf8' by hand and it seems to work.
Now, after I changed the action, let's wait until tomorrow to see if it gets automatically updated.

**Comment by VergeDX** [comment] 2020-06-19 11:32
Wait a sec... Why this CI still push when there is no new translation???  
see [https://github.com/lirios/text/commit/b88e493479fbb19c50c24bec8452d753501ce91e](https://github.com/lirios/text/commit/b88e493479fbb19c50c24bec8452d753501ce91e)

**Comment by plfiorini** [comment] 2020-06-19 11:58
The timestamp is updated when the .pot is regenerated.
It's a bug, the action should detect if only the timestamp was changed.

**Comment by plfiorini** [comment] 2020-07-10 06:20
Should be fixed with https://github.com/lirios/text/commit/0212bc4f8811ab63669734c164583c0679ffcf97
And since POT-Creation-Date is removed from the templates and translations, a diff is no longer produced when that is the only line changed.

**Closed as completed** 2020-07-10 08:08 UTC
Labels: bug
